version: "3.9"

services:
  pipeline:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend/gcp-credentials.json:/app/gcp-credentials.json:ro
      - ./pipeline/database.sql:/pipeline/database.sql:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    command: python execution.py

  api:
    build: ./backend
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/gcp-credentials.json:/app/gcp-credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    command: uvicorn api:app --host 0.0.0.0 --port 8080

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api